### PR TITLE
changed function arguments for TradeHistory

### PR DESCRIPTION
**Pull request by KLIM8D**
I found the variable number of arguments of the type interface difficult to work with.

### CODE REVIEW

**Comment by pharrisee** [comment]
Unfortunately doing it that way means that you **MUST** supply the parameters, the date parameters to the Poloniex returnTradeHistory end point are optional, at best you could change the method prototype to be:

func (p *Poloniex) TradeHistory(pair string, times ..time.Time) (tradeHistory TradeHistory, err error) {

and make a decision on the length of the times variadic variable.

Doing it the way you propose will not allow calls with just a start point, or just an end point.

**Comment by KLIM8D** [comment]
You're right. Didn't notice they were optional, sorry. Closing the PR.

**Comment by pharrisee** [comment]
No problem, nice to have some help with the API wrapper at last, anything else you think could be better let me know.

**Comment by pharrisee** [comment]
Just FYI, I've changed the prototype for both TradeHistory, PrivateTradeHistory and PrivateTradeHistoryAll to now be :

func (p *Poloniex) TradeHistory(pair string, dates ...int64) (tradeHistory TradeHistory, err error)
func (p *Poloniex) PrivateTradeHistory(pair string, dates ...int64) (tradeHistory TradeHistory, err error)
func (p *Poloniex) PrivateTradeHistoryAll(dates ...int64) (history PrivateTradeHistoryAll, err error)

You were correct in part that the previous prototypes were confusing.

Thanks for making me fix them. :+1:

**Pull request closed without merging**
